package com.jey.coursecritic.constants;

public enum CourseGenre {
    BUSINESS_ENTREPRENEURSHIP,
    TECHNOLOGY_PROGRAMMING,
    DESIGN_CREATIVITY,
    PERSONAL_DEVELOPMENT,
    LANGUAGE_LEARNING,
    SCIENCE_MATH,
    HEALTH_FITNESS,
    ACADEMIC_SUBJECTS,
    TEST_PREPARATION,
    IT_CERTIFICATION,
    ARTS_MUSIC,
    PHOTOGRAPHY_VIDEOGRAPHY
}
